# Generated by Django 3.1.2 on 2020-10-13 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('q1w1', models.CharField(max_length=3)),
                ('q1w2', models.CharField(max_length=3)),
                ('q1w3', models.CharField(max_length=3)),
                ('q1w4', models.CharField(max_length=3)),
                ('q1w5', models.CharField(max_length=3)),
                ('q2w1', models.CharField(max_length=3)),
                ('q2w2', models.CharField(max_length=3)),
                ('q2w3', models.CharField(max_length=3)),
                ('q2w4', models.CharField(max_length=3)),
                ('q2w5', models.CharField(max_length=3)),
                ('q3w1', models.CharField(max_length=3)),
                ('q3w2', models.CharField(max_length=3)),
                ('q3w3', models.CharField(max_length=3)),
                ('q3w4', models.CharField(max_length=3)),
                ('q3w5', models.CharField(max_length=3)),
                ('q4w1', models.CharField(max_length=3)),
                ('q4w2', models.CharField(max_length=3)),
                ('q4w3', models.CharField(max_length=3)),
                ('q4w4', models.CharField(max_length=3)),
                ('q4w5', models.CharField(max_length=3)),
                ('q5w1', models.CharField(max_length=3)),
                ('q5w2', models.CharField(max_length=3)),
                ('q5w3', models.CharField(max_length=3)),
                ('q5w4', models.CharField(max_length=3)),
                ('q5w5', models.CharField(max_length=3)),
                ('q6w1', models.CharField(max_length=3)),
                ('q6w2', models.CharField(max_length=3)),
                ('q6w3', models.CharField(max_length=3)),
                ('q6w4', models.CharField(max_length=3)),
                ('q6w5', models.CharField(max_length=3)),
                ('q7w1', models.CharField(max_length=3)),
                ('q7w2', models.CharField(max_length=3)),
                ('q7w3', models.CharField(max_length=3)),
                ('q7w4', models.CharField(max_length=3)),
                ('q7w5', models.CharField(max_length=3)),
                ('q8w1', models.CharField(max_length=3)),
                ('q8w2', models.CharField(max_length=3)),
                ('q8w3', models.CharField(max_length=3)),
                ('q8w4', models.CharField(max_length=3)),
                ('q8w5', models.CharField(max_length=3)),
                ('q9w1', models.CharField(max_length=3)),
                ('q9w2', models.CharField(max_length=3)),
                ('q9w3', models.CharField(max_length=3)),
                ('q9w4', models.CharField(max_length=3)),
                ('q9w5', models.CharField(max_length=3)),
                ('q10w1', models.CharField(max_length=3)),
                ('q10w2', models.CharField(max_length=3)),
                ('q10w3', models.CharField(max_length=3)),
                ('q10w4', models.CharField(max_length=3)),
                ('q10w5', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
