# Generated by Django 3.1.2 on 2020-10-13 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date_time',
        ),
        migrations.AddField(
            model_name='score',
            name='end_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Finishing time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='start_date_time',
            field=models.DateTimeField(null=True, verbose_name='Starting time'),
        ),
    ]
