# Generated by Django 3.1.2 on 2020-10-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201013_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_time',
        ),
    ]
