# Generated by Django 3.1.2 on 2020-10-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201014_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='answered',
        ),
    ]
