# Generated by Django 3.1.2 on 2020-10-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_questionset_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Exam starting time')),
                ('end', models.DateTimeField(verbose_name='Exam ending time')),
                ('duration', models.IntegerField(default=0, verbose_name='Exam duration (minutes)')),
                ('questions', models.IntegerField(default=1, verbose_name='Number of questions')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.exam'),
            preserve_default=False,
        ),
    ]
