# Generated by Django 3.1.2 on 2020-10-15 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20201015_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='score',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
