# Generated by Django 3.1.2 on 2020-10-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201015_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start',
            field=models.DateTimeField(verbose_name='Exam starting time'),
        ),
    ]
