# Generated by Django 3.1.2 on 2020-10-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201015_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='confidence',
            field=models.FloatField(choices=[(0.1, '0.1'), (0.2, '0.2'), (0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0')], default=0.0, verbose_name='Confidence'),
            preserve_default=False,
        ),
    ]
