# Generated by Django 3.1.2 on 2020-10-15 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201015_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AddField(
            model_name='questionset',
            name='answered',
            field=models.CharField(default='', max_length=1, verbose_name='Answered'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.score'),
        ),
        migrations.AddField(
            model_name='score',
            name='end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ending time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starting time'),
            preserve_default=False,
        ),
    ]
