# Generated by Django 3.1.2 on 2020-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201015_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Starting time'),
        ),
    ]
